### ISSUE TITLE
Android pull apk issue

### ISSUE THREAD

**Issue by newpIDC** [nettitude/scrounger#4]
Doesnt' seem to pull the apk even though the output says it completed. 
adb pull works fine.
![img](https://user-images.githubusercontent.com/2566488/44613605-97bd9900-a7e3-11e8-874a-1d39fd24def7.png)

**Comment by rdc-nettitude** [comment]
Are you sure the identifier is correct?
Can you run `misc/list_apps` and double check the identifier is there?

Also, if it is, run the pull_apk module again with `set debug true` and post the output here if you can.

Cheers

**Comment by newpIDC** [comment]
tried again same issue. when I enable debug via set debug true/True or set global debug True there isn't any additional output.

**Comment by newpIDC** [comment]
the temp dir is created on the device however the file is never copied to the temp dir. added a print statement to the command this is the result. also ran the adb commands in comparison

![a](https://user-images.githubusercontent.com/2566488/44794806-43b20c00-ab77-11e8-81ff-944754b55239.png)

**Comment by rdc-nettitude** [comment]
Checkout the [pull_apk](https://github.com/nettitude/scrounger/tree/pull_apk) branch.

I've added a few more checks to the `pull_apk` module and more debug logs.
If you could run it again with `set global debug true` that'd be great.

Cheers

**Comment by newpIDC** [comment]
`2018-08-30 08:51:52 -                         device : Running: which pm
2018-08-30 08:51:52 -                        general : Shell Command: which adb; exit 0
2018-08-30 08:51:52 -                        general : Shell Command: adb -s 0715f7a556402632 shell which pm; exit 0
2018-08-30 08:51:52 -                         device : Running: pm list packages -f -3
2018-08-30 08:51:52 -                        general : Shell Command: which adb; exit 0
2018-08-30 08:51:52 -                        general : Shell Command: adb -s 0715f7a556402632 shell pm list packages -f -3; exit 0
2018-08-30 08:51:54 -                       pull_apk : Creating remote temp directory
2018-08-30 08:51:54 -                         device : Running: mkdir -p /sdcard/scrounger-tmp
2018-08-30 08:51:54 -                        general : Shell Command: which adb; exit 0
2018-08-30 08:51:54 -                        general : Shell Command: adb -s 0715f7a556402632 shell mkdir -p /sdcard/scrounger-tmp; exit 0
2018-08-30 08:51:54 -                         device : Running: ls -d /sdcard/scrounger-tmp
2018-08-30 08:51:54 -                        general : Shell Command: which adb; exit 0
2018-08-30 08:51:54 -                        general : Shell Command: adb -s 0715f7a556402632 shell ls -d /sdcard/scrounger-tmp; exit 0
2018-08-30 08:51:54 -                       pull_apk : Pulling apk file
2018-08-30 08:51:54 -                         device : Running: which pm
2018-08-30 08:51:54 -                        general : Shell Command: which adb; exit 0
2018-08-30 08:51:54 -                        general : Shell Command: adb -s 0715f7a556402632 shell which pm; exit 0
2018-08-30 08:51:54 -                         device : Running: pm list packages -f -3
2018-08-30 08:51:54 -                        general : Shell Command: which adb; exit 0
2018-08-30 08:51:54 -                        general : Shell Command: adb -s 0715f7a556402632 shell pm list packages -f -3; exit 0
2018-08-30 08:51:56 -                         device : Running: mkdir -p /sdcard/scrounger-tmp
2018-08-30 08:51:56 -                        general : Shell Command: which adb; exit 0
2018-08-30 08:51:56 -                        general : Shell Command: adb -s 0715f7a556402632 shell mkdir -p /sdcard/scrounger-tmp; exit 0
2018-08-30 08:51:56 -                         device : Running: which su
2018-08-30 08:51:56 -                        general : Shell Command: which adb; exit 0
2018-08-30 08:51:56 -                        general : Shell Command: adb -s 0715f7a556402632 shell which su; exit 0
[-] Exception: su binary not found.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/scrounger/console/interactive.py", line 191, in do_run
    result = module.run()
  File "/usr/local/lib/python2.7/dist-packages/scrounger/modules/misc/android/pull_apk.py", line 56, in run
    self.device.pull_apk(self.identifier, remote_dir, filename)
  File "/usr/local/lib/python2.7/dist-packages/scrounger/core/device.py", line 876, in pull_apk
    self.root_execute("cp {} {}".format(apk_path, dest_apk_path))
  File "/usr/local/lib/python2.7/dist-packages/scrounger/core/device.py", line 661, in root_execute
    return _root_execute(command)
  File "/usr/local/lib/python2.7/dist-packages/scrounger/utils/general.py", line 330, in wrapper
    "{} binary not found.".format(self._binary), self._binary)
AndroidBinaryNotFoundException: su binary not found.
`

**Comment by rdc-nettitude** [comment]
Ok, fixed it. The problem is that scrounger required `su` to pull the APK and it couldn't find it in your device's PATH.
For some reason I though it needed root to do it but it seems to work fine without it.

Do you want to check it again?

I think you'll run into more of the same problem - other modules will try to use the `su` binary to perform some actions.

**Comment by newpIDC** [comment]
It works now.  thanks!
this is just my opinion you should have logic to try with su and if that fails try normal. this way you could analyze things with root privs and without.  awesome work though thanks again.
